### PR TITLE
Version 2  - Migrate Settings to DB -- Add Telegram and Email Subscription Support

### PR DESCRIPTION
**Pull request by yigitkeremoktay**
This branch is unstable and should only be used for testing purposes.
Thanks to @thnilsen and @jhuesser for Telegram and E-Mail Subscription.

This PR will let you know when it is stable.

### CODE REVIEW

**Comment by Pryx** [comment]
Thank you so much for this! Will review as soon as possible :)

**Comment by yigitkeremoktay** [comment]
@Pryx This is unstable please wait until we finish all the work. We also created a fork with @thnilsen to have the unstable features. That way we don't have to wait unil your busy schedule is over.:) if you want to try the bleeding edge features https://github.com/yigitkeremoktay/server-status

**Comment by yigitkeremoktay** [comment]
I will notify you when this is ready to be merged

**Comment by yigitkeremoktay** [comment]
@Pryx you may start reviewing as it is mostly complete and we can merge it when it is fully ready.
Hope you are excited for the new version :) 

You can check our process here in master https://github.com/yigitkeremoktay/server-status

**Comment by yigitkeremoktay** [comment]
We are currently working on this update! Hold tight! It will be ready to merge soon.

**Pull request merged**
