### PR TITLE
Update bootstrap

### PR DESCRIPTION
**Pull request by Tealk**
fixes from #143 are included

- Lifted to bootstrap 5
- cleaned up main.css
- fixed some beauty bugs
- replaced glyph with fontawesome
- colors obtained from bootstrap

Known issues
#142

### CODE REVIEW

**Comment by yigitkeremoktay** [comment]
We will be reviewing your code shortly and merging if all code is suitable.
Thanks for your contribution.

**Comment by yigitkeremoktay** [comment]
Currently Found Issues:

- [ ] Install Page is completely broken.

**Comment by Tealk** [comment]
>  Install Page is completely broken.

What do you mean by complete? I only see missing icons and the input fields are not nicely placed

**Comment by yigitkeremoktay** [comment]
> > Install Page is completely broken.
> 
> What do you mean by complete? I only see missing icons and the input fields are not nicely placed

Technically that is everything. :)

**Comment by Tealk** [comment]
yes i see there are still some classes not bootstrap 5 compatible
I am in the process of adapting this

**Comment by yigitkeremoktay** [comment]
> yes i see there are still some classes not bootstrap 5 compatible
> I am in the process of adapting this

Sure, message when it is ready for us to test.

**Comment by Tealk** [comment]
you are welcome to have a look at the rest ;)

**Comment by Tealk** [comment]
done @yigitkeremoktay 😄

**Comment by Tealk** [comment]
I hope you don't mind SASS but it's so much easier to create stylesheets, otherwise I don't see any more bugs at the moment

I am curious about your feedback

**Comment by Tealk** [comment]
how can I insert a new variable for the translation?

**Pull request merged**
